version: '3'

services:
  zookeeper:
    image: zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
    networks:
      - kafka_memgraph_network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - kafka_memgraph_network
    depends_on:
      - zookeeper

  memgraph:
    image: memgraph/memgraph-platform:latest
    container_name: memgraph
    ports:
      - "7687:7687"
      - "3000:3000"
    networks:
      - kafka_memgraph_network

networks:
  kafka_memgraph_network:
    driver: bridge
